aws_access_key = "****************************************"
aws_secret_key = "****************************************"
private_key_path = "~/keys/terraform-ec2-key"
bucket_name = "k8cltstuniquebucket202011"
environment_tag = "development"
billing_code_tag = "BILL007"
